# Generated by Django 3.2 on 2024-08-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240731_1925'),
        ('reviews', '0002_auto_20240731_2242'),
    ]

    operations = [
    ]
