# Generated by Django 3.2 on 2024-08-08 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_title_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('id', 'name', 'year'), 'verbose_name': 'произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть больше или равна 1.'), django.core.validators.MaxValueValidator(10, message='Оценка не может быть больше 10.')], verbose_name='Оценка произведения'),
        ),
    ]
